name: Windows

on:
  push:
    paths-ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/mac.yml'
      - '.gitignore'
      - 'mac/**'
      - 'src/plugins/au/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        submodules: 'true'
    - uses: microsoft/setup-msbuild@v2
    - run: msbuild /p:Configuration="Release" /p:Platform="x64" win/amsynth.sln
    - run: iscc win/installer.iss
    - uses: actions/upload-artifact@v4
      with:
        name: amsynth-windows-installer-${{ github.sha }}
        path: win/amsynth_*.exe
